version: 3
automerge: true
workspace: default
projects:
- name: diplom_netology
  dir: diplom_netology
  workflow: pull-request
  terraform_version: latest
  allow_custom_workflows: false
  apply_requirements: [approved]