- name: install docker and kubectl
  hosts: all
  become: true
  remote_user: ubuntu
  roles:
    - docker_install
    - k8s_install

- name: create cluster
  hosts: kube_control_plane
  become: true
  remote_user: ubuntu
  roles:
    - k8s_create_cluster

- name: node invite
  hosts: kube_node
  become: true
  remote_user: ubuntu
  roles:
    - node_invite

- name: monitoring
  hosts: k8s-master-1
  remote_user: ubuntu
  roles:
    - gaps
