---
# tasks file for k8s_create_cluster
- name: Check if /etc/kubernetes/admin.conf exists
  stat:
    path: /etc/kubernetes/admin.conf
  register: admin_conf_exists

- name: Initialize the Kubernetes cluster using kubeadm # инициализируем кластер
  become: true
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --service-cidr=10.96.0.0/12
  register: kubeadm_init_result
  until: kubeadm_init_result.rc == 0
  retries: 3
  delay: 15
  when: not admin_conf_exists.stat.exists

- name: get permission # даем доступ для обычного пользователя
  shell: "{{ item }}"
  become_user: ubuntu
  with_items:
   - mkdir -p $HOME/.kube
   - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
   - sudo chown $(id -u):$(id -g) $HOME/.kube/config


- name: Install calico pod network # устанавливаем calico pod network
  become: false
  shell: "{{ item }}"
  with_items:
   - curl https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml -O
   - kubectl apply -f calico.yaml

- name: Generate join command # показываем команду с добавлением ноды и записываем ее в переменную
  become_user: ubuntu
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file # создаем локальный файл и добавляем туда переменную для присоединения ноды
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
