name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  TF_VAR_BUCKET: ${{secrets.BUCKET}}
jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.8.5'

      - name: Initialize Terraform
        run: |
          cd ./terraform/
          ls -la
          terraform init -backend-config="bucket=${{ secrets.BUCKET }}" -backend-config="secret_key=${{ secrets.SECRET_KEY }}" -backend-config="access_key=${{ secrets.ACCESS_KEY }}"

      - name: Validate Terraform configuration
        run: |
          ls -la
          cd ./terraform/
          terraform validate

      # - name: Plan changes
      #   run: terraform plan

      - name: Apply changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd ./terraform/
          ls -la
          terraform apply
        
  destroy-infrastructure:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'destroy'
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
              terraform_version: '1.8.5'

        - name: Initialize Terraform
          run: terraform init

        - name: Destroy infrastructure
          run: terraform destroy -auto-approve