name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.8.5'

      # - name: Configure Terraform Environment
      #   run: |
      #     cd terraform/

      - name: Initialize Terraform
        run: |
          cd ./terraform/
          terraform init -backend-config="bucket=${{ secrets.BUCKET }}" -backend-config="secret_key=${{ secrets.SECRET_KEY }}" -backend-config="access_key=${{ secrets.ACCESS_KEY }}"

      - name: Validate Terraform configuration
        run: |
          cd ./terraform/
          terraform validate

      - name: Plan changes
        run: |
          cd ./terraform/
          echo "export bucket=${{ secrets.BUCKET }}" >> $GITHUB_ENV
          echo "export access_key=${{ secrets.ACCESS_KEY }}" >> $GITHUB_ENV
          echo "export secret_key=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
        
          terraform plan -var="bucket=${{ secrets.BUCKET }}" -var="access_key=${{ secrets.ACCESS_KEY }}" -var="secret_key=${{ secrets.SECRET_KEY }}" -var="cloud_id=${{ secrets.YANDEX_CLOUD_CLOUD_ID }}" -var="folder_id=${{ secrets.YANDEX_CLOUD_FOLDER_ID }}" -var="token=${{ secrets.YANDEX_CLOUD_TOKEN }}"

      - name: Apply changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          cd ./terraform/
          terraform apply

        
  destroy-infrastructure:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'destroy'
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
              terraform_version: '1.8.5'

        - name: Initialize Terraform
          run: terraform init

        - name: Destroy infrastructure
          run: terraform destroy -auto-approve